//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется light.rc
//
#define IDS_SCRIPTFILT                  1
#define IDR_MANIFEST                    1
#define IDS_TEXTFILT                    2
#define IDSTART                         3
#define ID_DETECT                       3
#define IDOVER                          3
#define IDUSE                           3
#define IDC_MM_HELP                     3
#define IDPRIVATE                       3
#define IDS_SOUNDFILT                   3
#define IDC_1DAY                        3
#define IDCLEAR                         4
#define IDDEFAULT                       4
#define IDEXTENDED                      4
#define IDRESET                         4
#define IDDIALBREAK                     4
#define IDSTATUSREPORT                  4
#define IDTEST                          4
#define ID_OTHERLINES                   4
#define IDS_QUERYFILT                   4
#define IDC_TRANSLATE                   4
#define IDADD                           5
#define IDABORTSESSION                  5
#define IDEXTSEARCH                     5
#define IDAPPLY                         5
#define IDS_QRESFILT                    5
#define IDC_PURGEONE                    5
#define IDC_3DAYS                       5
#define IDSETONLY                       6
#define IDCHECK                         6
#define IDS_ALLFILES                    6
#define IDC_WEEK                        6
#define IDDELETE                        7
#define IDTESTSOUND                     7
#define IDS_DESCRFILT                   7
#define IDC_MONTH                       7
#define IDSTOPSOUND                     8
#define IDS_EXECFILT                    8
#define IDS_E_NOTCOR                    9
#define ID_INTERNETGATE                 10
#define IDS_W_FILLIT                    10
#define IDS_W_NOEXEC                    11
#define IDS_TEXT_SAMPLES                12
#define IDS_EMPTY_PATTERNS              13
#define IDS_DEFSOUNDS                   14
#define IDS_ALREADYRUN                  15
#define IDM_ABOUTBOX                    0x0010
#define IDS_CFGNOTAVAIL                 16
#define IDS_INVALIDCHAR                 17
#define IDS_SYSERROR                    18
#define IDS_SKINFILT                    19
#define IDD_ABOUTBOX                    100
#define IDC_GOTOURL                     100
#define ID_USERMARK_SET                 101
#define IDC_MAILTO                      101
#define IDD_MAIN_WINDOW                 102
#define ID_USERMARK_CLEAR               102
#define ID_USERMARK_TOGGLE              103
#define ID_TOPREVAREA                   108
#define ID_TONEXTAREA                   109
#define ID_TOGGLE_STRUCT                111
#define ID_COPY_FROM                    112
#define ID_COPY_TO                      113
#define ID_COPY_SUBJECT                 114
#define IDC_DELIVTIME                   115
#define IDC_BINARY_INSERT               117
#define IDC_BBSNAME                     118
#define ID_SPACEPRESSED                 119
#define ID_PLUSPRESSED                  120
#define ID_MINUSPRESSED                 121
#define ID_MULTIPLYPRESSED              122
#define ID_DIVIDEPRESSED                123
#define IDC_FILEREQUEST                 124
#define IDC_ROT13                       126
#define ID_ADDR_PASTE                   127
#define ID_LIST_BADXFER                 128
#define IDR_MENU_ENG                    129
#define ID_SWITCH_CODING                131
#define ID_SAVEORIGIN                   132
#define ID_DELETE_SELECTED              133
#define ID_SUBJ_PASTE                   134
#define IDC_TOWN                        136
#define ID_SET_ENG                      137
#define ID_SET_GER                      138
#define ID_SET_RUS                      139
#define ID_SET_FRE                      140
#define ID_CONFIG                       142
#define IDD_AREASELECT                  143
#define IDC_PAGE_TREE                   143
#define IDD_MAIN_CONFIG                 144
#define IDD_CFG_DIRS                    145
#define IDC_DLG_FRAME                   145
#define IDD_CFG_BOSS                    146
#define IDC_CAPTION_BAR                 146
#define IDC_ANSWER_COMMAND              147
#define IDD_CFG_EDITOR                  148
#define IDD_ISDN_CONFIGURATIONS         148
#define IDD_CFG_AREA                    149
#define IDD_CFG_PACKER                  150
#define IDD_SIMPLE_SEARCH               151
#define IDD_STAT_PURGE                  152
#define IDD_STAT_MAILER                 153
#define IDD_STAT_TOSS                   154
#define IDD_CFG_SOUND                   157
#define IDD_CFG_TEMPLATE                158
#define IDD_WRITMAIL640                 159
#define ID_OEMTEXT                      159
#define IDD_CHANGE_TEMPLATE             160
#define ID_ANSITEXT                     160
#define IDC_STATUS_BAR                  161
#define IDC_CFG_HARDWARE                162
#define ID_RESTORE                      162
#define IDC_REPLACEDIALOG               163
#define IDD_MODEM_DETECT                164
#define IDC_QUERY                       164
#define IDD_ADRBOOK                     165
#define IDD_ADDRBOOK                    165
#define IDC_FILTER                      165
#define IDD_FREQ                        166
#define IDD_CFG_NODELIST                167
#define IDD_MESSAGEBOX                  168
#define IDD_SELECT_FROM_NODELIST        169
#define IDD_CFG_TWITS                   170
#define IDD_CFG_COLOR                   171
#define IDD_FREQ_SELECT                 172
#define IDD_SCRIPT_EDITOR               174
#define IDD_STAT_NLCOMP                 175
#define IDD_TIMEOUTS                    176
#define IDD_CHANGE_DEST                 177
#define IDD_CFG_CARBONS                 178
#define IDD_ECHO_FILELIST               179
#define IDD_TRAFFIC                     181
#define IDD_QUICK_SETUP                 182
#define IDD_FILELIST_REQUEST            184
#define IDD_ADD_FILELIST                185
#define IDD_CFG_OTHERS                  186
#define IDD_INFO_ADDRESS                188
#define IDD_TEXT_IMPORT                 190
#define IDD_CFG_TEXTIMP                 190
#define IDD_LOGFILE_DISPLAY             191
#define IDD_CFG_LOGFILES                192
#define IDD_CFG_PERSONAL                194
#define IDD_MANUAL_AREA_ORDER           195
#define IDD_CFG_FILTER                  196
#define IDD_CHAR_CONVERSION             199
#define IDD_CROSSPOST                   200
#define IDD_CFG_AREA_MULTIPLE           201
#define IDD_CFG_PHONES                  202
#define IDD_CHOOSE_SAVE                 204
#define IDD_OUTBOUND_VIEW               205
#define IDD_XFERFLS_EDIT                206
#define IDD_CFG_PRIVNODES               208
#define IDD_OUTBOUND_MAIL_VIEW          209
#define IDD_RECIPIENT_LIST              215
#define IDD_CHOOSE_IMPORT               216
#define IDD_EVENTS                      217
#define IDD_SEARCH_REPLACE              218
#define IDD_TEXT_REPLACEMENT            220
#define IDD_CFG_TEXTREPL                220
#define IDD_CFG_PRINT                   222
#define IDD_MESSAGEBOX_T                224
#define IDD_CFG_INCOME                  225
#define IDD_CFG_INRINGS                 227
#define IDD_EXT_SEARCH                  228
#define IDD_RESULT_FORMAT               230
#define IDD_CFG_DESIGN                  232
#define IDD_MM_SELECTION                233
#define IDD_BMP_VIEW                    235
#define IDD_CFG_GATE                    236
#define IDD_CFG_EXTFREQ                 237
#define IDD_ADJUST_SUBJ_LIST            239
#define IDD_CFG_MAGIC                   240
#define IDD_CFG_REQPATH                 241
#define IDD_CFG_REMOTE                  245
#define IDD_SEARCH_AREA_SELECTION       246
#define IDD_CFG_TICS                    249
#define IDD_HATCHDLG                    250
#define IDD_TIC_EDITOR                  251
#define IDD_INADR_FOUND                 252
#define IDD_START_BROWSER               256
#define IDD_SELECT_EV_BOSS              257
#define IDD_CHOOSE_MARK                 258
#define IDD_COST_BASE                   259
#define IDD_COST_USER                   260
#define IDD_CFG_COST                    260
#define IDD_COSTANAL                    262
#define IDD_INOUT_HIST                  263
#define IDD_CFG_FAX                     264
#define IDD_CHOOSE_AUTOSAVE             265
#define IDD_MANUAL_POLL                 266
#define IDD_BBS_USERS                   268
#define IDD_BBS_LEVELS                  269
#define IDD_BBS_MAIN                    270
#define IDD_BBS_AREA                    272
#define IDD_VALUE_AREAFIX               273
#define IDD_FLOATING_BAR                274
#define IDD_CFG_MMEDIA                  275
#define IDD_SELECT_MODEM                276
#define IDD_PRESENT_AGAIN               277
#define IDD_REPOST                      277
#define IDD_PRESENT_INFO                278
#define IDD_REPOST_FOLDER               278
#define IDB_SPLASH                      300
#define IDB_ABOUT                       301
#define IDB_CODANSI                     302
#define IDB_CODOEM                      303
#define IDB_COM1_OFF                    304
#define IDB_COM1_ON                     305
#define IDB_COM2_OFF                    306
#define IDB_COM2_ON                     307
#define IDB_ISDN_OFF                    308
#define IDB_ISDN_ON                     309
#define IDR_ACCELS                      387
#define IDR_MAILER                      400
#define IDR_PURGER                      401
#define IDR_TOSSER                      402
#define IDI_PHOENIX                     500
#define IDD_CFG_KLUDGES                 501
#define IDI_ABORT                       501
#define IDC_LIST_BAD_XFER               502
#define IDI_ASAVE                       502
#define IDD_CFG_BADXFER                 503
#define IDI_EXIT                        503
#define IDI_FILT                        504
#define IDC_EDIT_REALNAME               505
#define IDI_FIND                        505
#define IDC_EDIT_BADNAME                506
#define IDI_FREQ                        506
#define IDI_MACRO1                      507
#define IDI_MACRO2                      508
#define IDC_EDIT_FILESIZE               509
#define IDI_MACRO3                      509
#define IDC_EDIT_FILE_TIME              510
#define IDI_MACRO4                      510
#define IDI_MACRO5                      511
#define IDI_MAILER                      512
#define IDI_NEW                         513
#define IDI_NEXT                        514
#define IDI_PREV                        515
#define IDI_PURGER                      516
#define IDI_QUOTE                       517
#define IDI_QUOTEA                      518
#define IDI_TOSSER                      519
#define IDI_CODA                        520
#define IDI_ARROWUP                     520
#define IDI_CODO                        521
#define IDI_ARROWDN                     521
#define IDI_EMPTY                       522
#define IDR_POP_ENG                     532
#define IDD_CFG_SERVICES                554
#define IDD_DESIGN                      556
#define IDD_CFG_HARDWARE                559
#define IDD_GUARD                       562
#define IDD_SELCOLOR                    563
#define IDD_COLORBTN                    565
#define IDD_ADDRSELECT                  567
#define IDI_FIPS                        599
#define IDC_EDIT                        1000
#define IDC_USEINTHISAREAS              1001
#define IDC_LIST                        1002
#define IDC_LIST_SUBJECT                1003
#define IDC_MEMBERS                     1003
#define IDC_PATTERNS_LIST               1003
#define IDC_MMLIST                      1003
#define IDC_LISTB                       1003
#define IDC_FROM                        1004
#define IDC_TO                          1005
#define IDC_FROM_ADDRESS                1006
#define IDC_TEXT_FROM                   1007
#define IDC_TO_ADDRESS                  1008
#define IDC_TEXT_TO                     1009
#define IDC_SUBJECT                     1010
#define IDC_CREATE                      1011
#define IDC_RECEIVE                     1012
#define IDC_TEXT_SUBJECT                1013
#define IDC_BUTTON1                     1016
#define IDC_BUTTON2                     1017
#define IDC_DOWN                        1017
#define IDC_SAVE                        1017
#define IDC_SEND                        1017
#define IDC_CASESENS                    1017
#define IDC_BUTTON12                    1018
#define IDC_SEND_COMPLETE               1018
#define IDC_REST                        1018
#define IDC_MANUAL_ORDER                1019
#define IDC_SAVE_UDEF                   1019
#define IDC_TICFILES                    1019
#define IDC_RESCAN                      1020
#define IDC_BUTTON18                    1021
#define IDC_EDIT_FOCUS                  1032
#define IDC_AREACFG                     1034
#define IDC_PGUP                        1034
#define IDC_LIST1                       1035
#define IDC_ORIGIN_LIST                 1036
#define IDC_REQUEST                     1036
#define IDC_SYSTEMS                     1036
#define IDC_STATUS                      1037
#define IDC_FREQ                        1038
#define IDC_BASEDIR                     1038
#define IDC_MESSAGEBASE                 1039
#define IDC_UTILITIES                   1040
#define IDC_INBOUND                     1042
#define IDC_DEFAULT                     1043
#define IDC_cfg_prename                 1044
#define IDC_ORIGIN_DEFAULT              1044
#define IDC_ORIGIN_DEFAULT_NEW          1045
#define IDC_DUPE_CHECK                  1045
#define IDC_OUTBOUND                    1045
#define IDC_ADD                         1046
#define IDC_cfg_aftername               1046
#define IDC_DELETE                      1047
#define IDC_REMOVECALL                  1047
#define IDC_cfg_systemname              1047
#define IDC_CLEARLIST                   1048
#define IDC_CLEAR                       1048
#define IDC_ORIGIN_DELETE               1048
#define IDC_cfg_location                1048
#define IDC_INFO_ADDRESS                1048
#define IDC_DELETE_THIS_PACKET          1048
#define IDC_IMPORT_TIC                  1048
#define IDC_ADD2                        1048
#define IDC_ADDRBOOK                    1048
#define IDC_BOSSNAME                    1049
#define IDC_ORIGIN_ADD                  1049
#define IDC_cfg_telephone               1049
#define IDC_SCHEDULE                    1049
#define ID_INFO_SENDER                  1049
#define IDC_DELETE2                     1049
#define IDC_PACKERTYPE                  1050
#define ID_INFO_RECIPIENT               1050
#define IDC_INFO_OTHERLINES             1050
#define IDC_SYSBOSS                     1050
#define IDC_CHANGE2                     1050
#define IDC_CLEAREDITS                  1051
#define IDC_PACKERTYPE2                 1051
#define IDC_LAST_SCALE                  1051
#define IDC_PATTERNSEARCH               1051
#define IDC_CHANGE1                     1051
#define IDC_SYSOPNAME                   1052
#define IDC_LAUFZEIT                    1052
#define IDC_ALIASES                     1052
#define IDC_AFIX_PLUS                   1053
#define IDC_FFIX_PLUS                   1054
#define IDC_GOLDED_COMP                 1054
#define IDC_SET                         1055
#define IDC_HIDE_BEG_EMP_LINES          1056
#define IDC_ASDEFAULT                   1056
#define IDC_EXPORT                      1056
#define IDC_CHANGEB                     1056
#define IDC_IMMEDIATE_UPDATE            1058
#define IDC_OPEN_MAILER                 1059
#define IDC_OPEN_TOSSER                 1060
#define IDC_OPEN_PACKER                 1061
#define IDC_FIDOADDRESS                 1062
#define IDC_COLORED                     1062
#define IDC_PHONENUMBER                 1063
#define IDC_AUTOSCROLL                  1063
#define IDC_MYPOINTNUMBER               1064
#define IDC_STRUCT_SUBJECT              1064
#define IDC_SESSIONPASSWORD             1065
#define IDC_MAIL_NAVIGATION             1065
#define IDC_AFIX_NAME                   1066
#define IDC_DONT_DELETED                1066
#define IDC_AFIX_PASSWORD               1067
#define IDC_AREATAG                     1067
#define IDC_FFIX_NAME                   1068
#define IDC_DESCRIPTION                 1068
#define IDC_FFIX_PASSWORD               1069
#define IDC_AKA                         1069
#define IDC_FL_PACKEDNAME               1070
#define IDC_GROUP                       1070
#define IDC_FL_UNPACKEDNAME             1071
#define IDC_NUMBER                      1071
#define IDC_NRMAILS                     1072
#define IDC_EDIT_MAXNR                  1073
#define IDC_ECHOFILENAME                1074
#define IDC_COMBO1                      1074
#define IDC_NEW_PACKEDNAME              1075
#define IDC_P1                          1075
#define IDC_DD_DEFGROUP                 1075
#define IDC_NEW_UNPACKEDNAME            1076
#define IDC_AGE_CREATE                  1076
#define IDC_NAME                        1076
#define IDC_AGECREATE                   1076
#define IDC_AGE_RECIPT                  1077
#define IDC_PACKSTRING                  1077
#define IDC_ARCFILENAME                 1077
#define IDC_INFOZEILE                   1077
#define IDC_PACKCMD                     1077
#define IDC_EDIT_AGE_CREATE             1078
#define IDC_DEPACKSTRING                1078
#define IDC_EDIT1                       1078
#define IDC_EDIT_NICKNAME               1078
#define IDC_UNPACKCMD                   1078
#define IDC_NICKNAME                    1078
#define IDC_EDIT_AGE_RECIPT             1079
#define IDC_P2                          1079
#define IDC_IGNORECASE                  1079
#define IDC_EDIT_MAILS                  1079
#define IDC_MAILSTOTAL                  1079
#define IDC_ORIGIN_EDIT                 1079
#define IDC_SYSTEM                      1079
#define IDC_FOOTER                      1079
#define IDC_FILENAME                    1079
#define IDC_TRANSLATED                  1079
#define IDC_WAITTIME                    1079
#define IDC_CDPHONE                     1079
#define IDC_EDIT_AGE_CREATE2            1079
#define IDC_EDIT5                       1079
#define IDC_P3                          1080
#define IDC_HEADER                      1080
#define IDC_BYTESTOTAL                  1080
#define IDC_SYSTEMNAME                  1080
#define IDC_LOOPCOUNTER                 1080
#define IDC_CDPASSWORD                  1080
#define IDC_EDIT_AGE_RECIPT2            1080
#define IDC_EDIT6                       1080
#define IDC_AGERECIPT                   1080
#define IDC_P5                          1081
#define IDC_MESSAGETEXT                 1081
#define IDC_BYTESSAVED                  1081
#define IDC_LOACTION                    1081
#define IDC_44                          1081
#define IDC_EDIT_SUBJECT                1081
#define IDC_ADDITIONAL_DAYS             1081
#define IDC_EDIT_OUTWAIT                1081
#define IDC_EDIT_BBS                    1081
#define IDC_PAUSE_S2                    1081
#define IDC_EDIT_TEL                    1081
#define IDC_P7                          1082
#define IDC_MAILSREMOVED                1082
#define IDC_TIMEELAPSED                 1082
#define IDC_55                          1082
#define IDC_EDIT_BOSS1                  1082
#define IDC_EDIT_LOCATION               1082
#define IDC_NR_ISDN                     1082
#define IDC_EDIT_MAILCONT               1082
#define IDC_EDIT_MODEMFAX               1082
#define IDC_ATTRLIST                    1082
#define IDC_P4                          1083
#define IDC_66                          1083
#define IDC_EDIT_BOSS2                  1083
#define IDC_PAUSE_ISDN                  1083
#define IDC_EDIT_AKA                    1083
#define IDC_EDIT_LINES                  1083
#define IDC_EDIT7                       1083
#define IDC_P6                          1084
#define IDC_77                          1084
#define IDC_EDIT_BOSS3                  1084
#define IDC_EDIT_GROUPS                 1084
#define IDC_P8                          1085
#define IDC_AREA_PROZ                   1085
#define IDC_88                          1085
#define IDC_EDIT_MAXTRY                 1085
#define IDC_EDIT_REMAIN                 1085
#define IDC_P9                          1086
#define IDC_MAILS_PROZ                  1086
#define IDC_99                          1086
#define IDC_EDIT_CAUTION                1086
#define IDC_P10                         1087
#define IDC_EDIT_AREA                   1087
#define IDC_AREAS                       1087
#define IDC_00                          1087
#define IDC_EDIT_CAUTION2               1087
#define IDC_ICON_BUTTON_MODEM           1088
#define IDC_EDIT_CAUTION3               1088
#define IDC_ICON_BUTTON_PACKER          1089
#define IDC_CPS                         1089
#define IDC_ICON_BUTTON_PURGE           1090
#define IDC_BYTESTRANSF                 1090
#define IDC_PROZ                        1091
#define IDC_PKTSTOTAL                   1092
#define IDC_BROWSE                      1093
#define IDC_PATH                        1094
#define IDC_BROWSE_VIEWER               1094
#define IDC_BROWSE2                     1094
#define IDC_BROWSE3                     1095
#define IDC_ORIGIN_SET                  1096
#define IDC_BROWSE_VIEWER_BGFAX         1096
#define IDC_BROWSE4                     1096
#define IDC_BROWSE5                     1097
#define IDC_BROWSE6                     1098
#define IDC_BROWSE7                     1099
#define IDC_DEFAULT_QUOTE               1099
#define IDC_SET_QUOTE                   1099
#define IDC_FOOTER_SET                  1100
#define IDC_BROWSE8                     1100
#define IDC_BROWSE9                     1101
#define IDC_BROWSE10                    1102
#define IDC_RANDOM_QUOTE                1103
#define IDC_FOOTER_LIST                 1104
#define IDC_FOOTER_EDIT                 1105
#define IDC_FOOTER_DELETE               1106
#define IDC_FOOTER_ADD                  1107
#define IDC_FOOTER_DEFAULT              1108
#define IDC_FOOTER_TEXT                 1110
#define IDC_ORIGIN_TEXT                 1111
#define IDC_DEFAULT_NEW                 1112
#define IDC_SET_NEW                     1112
#define IDC_FOOTER_DEFAULT_NEW          1113
#define IDC_TEXT                        1115
#define IDC_FOOTER_TEXT_NEW             1115
#define IDC_ORIGIN                      1116
#define IDC_ORIGIN_TEXT_NEW             1116
#define IDC_RANDOM_NEW                  1117
#define IDC_ATTACH                      1119
#define IDC_FROM_FIDO                   1121
#define IDC_TMP                         1121
#define IDC_TO_FIDO                     1122
#define IDC_TABSIZE                     1122
#define IDC_CHECK_FILEATTACHED          1123
#define IDC_AUTOINDENT                  1123
#define IDC_ATTACH_CHK                  1123
#define IDC_INIT1                       1124
#define IDC_REQUEST_RECIPT              1124
#define IDC_TABTOSPACE                  1124
#define IDC_INIT2                       1125
#define IDC_SEND_DIRECT                 1125
#define IDC_INIT3                       1126
#define IDC_KILL_AFTER_SEND             1126
#define IDC_DIAL_COMMAND                1127
#define IDC_WORDWRAP                    1127
#define IDC_INFO                        1127
#define IDC_IMPORT                      1128
#define IDC_EQUALTABS                   1128
#define IDC_COMPORT                     1129
#define IDC_BAUD                        1130
#define IDC_CHAR_CONVERSION             1130
#define IDC_DATA8                       1131
#define IDC_FREEZEMAIL                  1131
#define IDC_PNONE                       1132
#define IDC_PRIVATE                     1132
#define IDC_RTS                         1133
#define IDC_DATA7                       1134
#define IDC_PODD                        1135
#define IDC_PEVEN                       1136
#define IDC_RMARGIN                     1136
#define IDC_1                           1137
#define IDC_2                           1138
#define IDC_XON                         1139
#define IDC_MODEMSELECT                 1140
#define IDC_INITDIAL1                   1142
#define IDC_INITDIAL2                   1143
#define IDC_INITDIAL3                   1144
#define IDC_FIDO                        1145
#define IDC_USE_INSTALLED               1145
#define IDC_AUTOAKA                     1146
#define IDC_ADDRESS                     1147
#define IDC_NODELIST                    1149
#define IDC_PHONE                       1149
#define IDC_UP                          1150
#define IDC_PASSWORD                    1150
#define IDC_PHONE2                      1150
#define IDC_QUEUE                       1151
#define IDC_FLAGS                       1151
#define IDC_CLEAR_QUEUE                 1152
#define IDC_SKIPCALL                    1152
#define IDC_PREF2                       1153
#define IDC_START_EVENTS                1153
#define IDC_CITYPF                      1153
#define IDC_NODELIST_TYPE               1154
#define IDC_STOP_EVENTS                 1154
#define IDC_NODELIST_NAME               1155
#define IDC_SETUP_EVENTS                1155
#define IDC_NODEDIFF_NAME               1156
#define IDC_EVENT_LOG                   1156
#define IDC_ORG                         1157
#define IDC_COUNTRYPF                   1157
#define IDC_INTERNAT                    1158
#define IDC_OFFICEPF                    1158
#define IDC_edithelp                    1159
#define IDC_BASECOLOR                   1161
#define IDC_FINDNEXT                    1161
#define IDC_NORMALTEXT                  1162
#define IDC_MAILTEXT                    1162
#define IDC_ODDQUOTE                    1163
#define IDC_INFORMATION                 1164
#define IDC_BASECOLOR_SUBJECT           1165
#define IDC_BACKGROUND_SUBJ             1165
#define IDC_NORMALTEXT_SUBJECT          1166
#define IDC_TEXT_SUBJ                   1166
#define IDC_NEVERDELETE                 1167
#define IDC_ARROW_SUBJ                  1167
#define IDC_RANGE                       1168
#define IDC_USEDOS                      1168
#define IDC_FILES                       1169
#define IDC_TRANSNAME                   1170
#define IDC_RANGE_SUBJECT               1170
#define IDC_CONT                        1171
#define ID_SWITCH_ATTR                  1171
#define IDC_HIGHLIGHT                   1171
#define IDC_FONTFACE                    1171
#define IDC_BOLD_BUTTON                 1172
#define IDC_CONVERT                     1172
#define ID_SWITCH_KLUDGE                1172
#define IDC_EDITFONTSZ                  1172
#define IDC_EDIT_UDEF_1                 1173
#define IDC_NEXT_AVAIL_SER              1173
#define IDC_FONTSZ                      1173
#define IDC_LOAD                        1174
#define IDC_TOGGLE_FROZEN               1174
#define ID_SWITCH_DEL                   1174
#define IDC_ABORT                       1175
#define IDC_UDEF_FIND_1                 1176
#define IDC_EDIT_UDEF_2                 1177
#define IDC_LASTONLY                    1177
#define IDC_EDIT_UDEF_3                 1178
#define IDC_FIRST_NON                   1178
#define IDC_CROSSJUMP                   1178
#define IDC_EDIT_UDEF_4                 1179
#define IDC_LAST_ALREADY                1179
#define IDC_LAST_READ                   1179
#define IDC_UDEF_FIND_2                 1180
#define IDC_UDEF_FIND_3                 1181
#define IDC_TRYCOUNTER                  1181
#define IDC_UDEF_FIND_4                 1182
#define IDC_CDSYSTEM                    1182
#define IDC_EDIT_UDEF_5                 1183
#define IDC_IGNORE_CASE                 1184
#define IDC_UDEF_FIND_5                 1184
#define IDC_STRING                      1185
#define IDC_EDIT_UDEF_6                 1185
#define IDC_AREALIST                    1186
#define IDC_DEST_AREA                   1186
#define IDC_UDEF_FIND_6                 1186
#define IDC_BOSS                        1187
#define IDC_NOT_COPY_AREAS              1187
#define IDC_EDIT_UDEF_7                 1187
#define IDC_BOSSCFG                     1188
#define IDC_UDEF_FIND_7                 1188
#define IDC_GENERIC1                    1189
#define IDC_EDIT_UDEF_8                 1189
#define IDC_UDEF_FIND_8                 1190
#define IDC_FILELIST                    1191
#define IDC_EDIT_UDEF_9                 1191
#define IDC_UDEF_FIND_9                 1192
#define IDC_EDIT2                       1193
#define IDC_EDIT_UDEF_10                1193
#define IDC_EDIT3                       1194
#define IDC_UDEF_FIND_10                1194
#define IDC_CASEINSENS                  1195
#define IDC_EDIT_UDEF_11                1195
#define IDC_LIST2                       1196
#define IDC_UDEF_FIND_11                1196
#define IDC_EDIT_UDEF_12                1197
#define IDC_UDEF_FIND_12                1198
#define IDC_EDIT_UDEF_13                1199
#define IDC_UDEF_FIND_13                1200
#define IDC_AUTOSTART_TOSSER            1203
#define IDC_EDIT_UDEF_15                1203
#define IDC_ROUTE                       1204
#define IDC_AUTORESCAN                  1204
#define IDC_UDEF_FIND_15                1204
#define IDC_EDIT4                       1205
#define IDC_PURGE_ON_EXIT               1205
#define IDC_GOTO                        1205
#define IDC_EDIT_UDEF_16                1205
#define IDC_SCROLLBAR1                  1206
#define IDC_STARTUP_EVENTS              1206
#define IDC_UDEF_FIND_16                1206
#define IDC_TOP                         1207
#define IDC_NO_INFOMAILS                1207
#define IDC_BOTTOM                      1208
#define IDC_NO_DETSEARCH                1208
#define IDC_PGDOWN                      1209
#define IDC_GLOBAL_AUTOSAVE             1209
#define IDC_FIDODROP                    1210
#define IDC_PURGE_SCANNED               1210
#define IDC_AREA_AFTER_LAST             1211
#define IDC_11                          1212
#define IDC_22                          1213
#define IDC_NORES                       1213
#define IDC_33                          1214
#define IDC_PACKOUTBOUND                1214
#define IDC_FIRST_DISPLAYED             1216
#define IDC_EMPTY_TEARLINE              1216
#define IDC_DIRECT                      1217
#define IDC_NO_NEWAREAINFO              1217
#define IDC_MAILER_LOGFILE              1218
#define IDC_INCREASE_MAILER_PRIORITY    1218
#define IDC_TOSSER_LOGFILE              1219
#define IDC_FLUSHFILE                   1219
#define IDC_PURGER_LOGFILE              1220
#define IDC_LMAILER                     1220
#define IDC_NO_TOOLTIPS                 1220
#define IDC_LTOSSER                     1221
#define IDC_EVENTS_LOGFILE              1221
#define IDC_NO_TICWORK                  1221
#define IDC_LPURGER                     1222
#define IDC_NODELIST_LOGFILE            1222
#define IDC_ROLLEN_LIGHT                1222
#define IDC_NEW_STRING                  1223
#define IDC_LEVENTS                     1223
#define IDC_COLOR_OF_STRING             1224
#define IDC_LNODELIST                   1224
#define IDC_CONVERT_LATIN               1224
#define IDC_COLOR_SELECT                1225
#define IDC_FILTER_RE                   1225
#define IDC_CHECK_POINTLIST             1226
#define IDC_POINTLIST_ZONE              1227
#define IDC_CCAREA                      1229
#define IDC_UNREAD                      1230
#define IDC_NOT_OLDER                   1231
#define IDC_C_IN_FROM                   1232
#define IDC_C_IN_TO                     1233
#define IDC_C_IN_SUBJECT                1234
#define IDC_OUTGOING                    1235
#define IDC_EDIT_DAYS                   1236
#define IDC_EDIT_FROM                   1237
#define IDC_EDIT_TO                     1238
#define IDC_NO_REPLY                    1239
#define IDC_EDIT_FROM2                  1239
#define IDC_EDIT_TO_FIDO                1239
#define IDC_NOFILTER                    1240
#define IDC_AGAIN                       1240
#define IDC_SINCE_LAST_POLL             1241
#define IDC_STATIC1                     1242
#define IDC_STATIC2                     1243
#define IDC_MARKEDONLY                  1243
#define IDC_STATIC3                     1244
#define IDC_HEADERONLY                  1244
#define IDC_STATIC4                     1245
#define IDC_EDIT_HEADER                 1245
#define IDC_STATIC5                     1246
#define IDC_EDIT_SHOWLAST               1246
#define IDC_STATIC6                     1247
#define IDC_FORZEN_ONLY                 1247
#define IDC_STATIC7                     1248
#define IDC_STATIC8                     1249
#define IDC_STATIC9                     1250
#define IDC_STATIC10                    1251
#define IDC_STATIC11                    1252
#define IDC_STATIC12                    1253
#define IDC_STATIC13                    1254
#define IDC_STATIC14                    1255
#define IDC_STATIC15                    1256
#define IDC_STATIC16                    1257
#define IDC_STATIC17                    1258
#define IDC_STATIC18                    1259
#define IDC_STATIC19                    1260
#define IDC_STATIC20                    1261
#define IDC_STATIC21                    1262
#define IDC_STATIC22                    1263
#define IDC_STATIC23                    1264
#define IDC_STATIC24                    1265
#define IDC_STATIC25                    1266
#define IDC_STATIC0                     1267
#define IDC_STATIC100                   1269
#define IDC_ENABLE_CHARACTER_CONVERSION 1271
#define IDC_EDIT_CHAR                   1272
#define IDC_EDIT_REPLACE                1273
#define IDC_UNMODIFIED                  1274
#define IDC_INCLUDE_CROSSPOST           1275
#define IDC_FIPSSTYLE                   1275
#define IDC_CURRENTSELECTED             1276
#define IDC_U_AKA                       1279
#define IDC_EDIT_TRANS_ORG              1283
#define IDC_EDIT_TRANS_TRANS            1284
#define IDC_EDIT_NUMBER                 1285
#define IDC_EDIT_ADD_ADDITIONAL_DAYS    1286
#define IDC_U_UPLINK                    1286
#define IDC_STATIC55                    1287
#define IDC_U_ENABLE_NR_OF_MAILS        1287
#define IDC_U_AGE_OF_CREATION           1288
#define IDC_STATIC56                    1288
#define IDC_U_AGE_OF_REACIPTION         1289
#define IDC_STATIC57                    1289
#define IDC_U_EDIT_NR_OF_MAILS          1290
#define IDC_U_EDIT_AGE_OF_CREATION      1291
#define IDC_U_EDIT_AGE_OF_RECIPTION     1292
#define IDC_U_EDIT_ADDITIONAL_DAYS      1293
#define IDC_EDIT_ADDITIONAL_DAYS        1294
#define IDC_STATIC66                    1295
#define IDC_GROUPNAME                   1296
#define IDC_STATIC77                    1298
#define IDC_STATIC_01                   1300
#define IDC_STATIC_02                   1301
#define IDC_STATIC50                    1302
#define IDC_TELEPHONE_NUMBER            1303
#define IDC_STATIC51                    1303
#define IDC_LIST_PKT                    1305
#define IDC_LIST_CONTENTS               1306
#define IDC_CHECK_FROM                  1308
#define IDC_STATIC45                    1309
#define IDC_FROMADDR                    1310
#define IDC_CHECK_TO                    1311
#define IDC_CHECK_SUBJECT               1312
#define IDC_ISDN_TRANSLATION            1312
#define IDC_INSTALL_DAYS                1313
#define IDC_ISDN_USE_2ND_MODEM          1313
#define IDC_MULTIMEDIA_INSERT           1314
#define IDC_CLIP_CUT                    1315
#define IDC_CLIP_PASTE                  1316
#define IDC_CLIP_COPY                   1317
#define ID_TO_PASTE                     1318
#define IDC_DELETE_GROUP                1319
#define IDC_DELETE_MEMBER               1320
#define IDC_ADD_MEMBER                  1321
#define IDC_FINDINET                    1321
#define IDC_EDIT_NAME                   1322
#define IDC_USERECIPIENT                1322
#define IDC_EDIT_FIDO                   1323
#define IDC_EDIT_NORMAL                 1323
#define IDC_STATIC34                    1324
#define IDC_EDIT_WEEKEND                1324
#define IDC_STATIC38                    1325
#define IDC_EDIT_GROUP                  1326
#define IDC_ADD_NEW_GROUP               1327
#define IDC_STATIC76                    1328
#define IDC_IMPORT_TEXT                 1329
#define IDC_OEMTEXT                     1329
#define IDC_UUENCODE                    1330
#define IDC_MULTIM                      1331
#define IDC_STATIC78                    1332
#define IDC_EDIT_INWAIT                 1333
#define IDC_STATIC345                   1334
#define IDC_STATIC542                   1335
#define IDC_ENABLE                      1337
#define IDC_DISABLE                     1338
#define IDC_RESTART_SEQUENCE            1339
#define IDC_EDIT_STATUS                 1340
#define IDC_ABORT_CURRENT_EVENT         1340
#define IDC_CHECK_THIS_ENABLED          1341
#define IDC_CHECK_MONDAY                1342
#define IDC_CHECK_THUESDAY              1343
#define IDC_CHECK_WEDNESDAY             1344
#define IDC_CHECK_THURSDAY              1345
#define IDC_CHECK_FRIDAY                1346
#define IDC_CHECK_SATURADAY             1347
#define IDC_CHECK_SUNDAY                1348
#define IDC_STATIC3453                  1349
#define IDC_FILE_ACTION_FAILED          1350
#define IDC_FILE_ACTION_OK              1351
#define IDC_EDIT_EXCLUDE                1352
#define IDC_DELETE_AFTER_SUCCESS        1352
#define IDC_SHOW_QUEUE                  1354
#define IDC_STATIC197                   1355
#define IDC_STATIC198                   1356
#define IDC_STATIC199                   1357
#define IDC_MQUEUE                      1358
#define IDC_SEARCH                      1359
#define IDC_EDIT_SEARCH                 1360
#define IDC_LOAD_QUERY                  1360
#define IDC_REPLACE                     1361
#define IDC_SAVE_QUERY                  1361
#define IDC_CHECK_CASESENS              1362
#define IDC_STOP_SEARCH                 1362
#define IDC_SEL_ALL                     1363
#define IDC_MAXIMUM                     1364
#define IDC_CLEAR_ALL                   1364
#define IDC_SECONDS                     1365
#define IDC_CLEAR_SEARCH                1365
#define IDC_DELAY                       1366
#define IDC_CLEAR_QUERY_LIST            1366
#define IDC_STATIC33                    1367
#define IDC_DISP_NEXT_Q_RESULT          1367
#define IDC_CHANGE                      1368
#define IDC_EDIT_STRING                 1369
#define IDC_EDIT_REPLACEMENT            1370
#define IDC_HIDDEN                      1373
#define IDC_CMD_LINE                    1374
#define IDC_EDIT_ERRORS                 1376
#define IDC_IGNORERR                    1376
#define IDC_MAILER_MAXSIZE              1378
#define IDC_MAILER_SHORT_TO             1379
#define IDC_TOSSER_MAXSIZE              1380
#define IDC_TOSSER_SHORT_TO             1381
#define IDC_PURGER_MAXSIZE              1382
#define IDC_PURGER_SHORT_TO             1383
#define IDC_EVENTS_MAXSIZE              1384
#define IDC_EVENTS_SHORT_TO             1385
#define IDC_STATIC88                    1387
#define IDC_NODELIST_MAXSIZE            1388
#define IDC_FIRST_MODEM                 1389
#define IDC_NODELIST_SHORT_TO           1389
#define IDC_SECOND_MODEM                1390
#define IDC_ISDN_LINE                   1391
#define IDC_SERVICE_EMSI                1398
#define IDC_EMSI                        1398
#define IDC_DISABLE_INCOMING            1399
#define IDC_SERVICE_MAILBOX             1400
#define IDC_NR_S1                       1400
#define IDC_BBS                         1400
#define IDC_NR_S2                       1401
#define IDC_PAUSE_S1                    1402
#define IDC_SERVICE_FAX                 1402
#define IDC_FAX                         1402
#define IDC_SERVICE_VOICE               1403
#define IDC_DD_FIELD                    1404
#define IDC_DD_CONTAINS                 1405
#define IDC_NOT                         1406
#define IDC_LOAD_RESULTS                1407
#define IDC_SAVE_RESULTS                1408
#define IDC_PROGRESS1                   1409
#define IDC_STATIC_NR_FOUND             1410
#define IDC_STATIC_123                  1411
#define IDC_STATIC352                   1412
#define IDC_STATIC876                   1413
#define IDC_CASE_SESITIVE               1414
#define IDC_ORED                        1415
#define IDC_DISPLAY                     1416
#define IDC_EDIT_FORMAT                 1416
#define IDC_EDIT_TABS                   1417
#define IDC_DISPLAY_ALL                 1417
#define IDC_DISPLAY_UDEF                1418
#define IDC_DISPLAY_TODAY               1418
#define IDC_ADD_COMMENT                 1419
#define IDC_DELETE_COMMENT              1420
#define IDC_EDIT_COMMENT                1421
#define IDC_MULTIMEDIA                  1422
#define IDC_PLAY_SOUNDS                 1423
#define IDC_TICBASIC                    1423
#define IDC_DD_NOTFOUND                 1424
#define IDC_WAVTYPE                     1424
#define IDC_DISPLAY_BMPS                1425
#define IDC_BMPTYPE                     1425
#define IDC_PLAYMAIL                    1426
#define IDC_SHOWBMP                     1426
#define IDC_EXT_TOOL                    1427
#define IDC_PLAYLINE                    1427
#define IDC_SHOWWAV                     1427
#define IDC_EDIT_PATH                   1428
#define IDC_EXT_TOOL_CFG                1428
#define IDC_PLAYDBLCLK                  1428
#define IDC_CHECK_16BIT                 1429
#define IDC_SLIDER1                     1431
#define IDC_SLIDER2                     1432
#define IDC_SLIDER3                     1433
#define IDC_EDIT_MAGIC                  1433
#define IDC_EDIT_PASSWORD               1434
#define IDC_EDIT_DESCRIPTION            1434
#define IDC_STATIC568                   1438
#define IDC_EDIT_WITH                   1440
#define IDC_CHECK_ENABLE                1441
#define IDC_CHECK_CC_NETMET             1442
#define IDC_CHECK_CC_ECHOMET            1443
#define IDC_STATIC639                   1445
#define IDC_BROWSE_AREAS                1446
#define IDC_EDIT_COPYTOAREA             1447
#define IDC_COMBO_UPLINK                1449
#define IDC_EDIT_ECHONAME               1450
#define IDC_EDT_ECHONAME                1450
#define IDC_EDIT_ECHO                   1452
#define IDC_CHECK1                      1453
#define IDC_CHECK_DONTDELETE            1454
#define IDC_NETMAILORIG                 1454
#define IDC_DONTDELETE                  1454
#define IDC_LBL_TEARLINE                1456
#define IDC_COMMANDLINE                 1458
#define IDC_EDIT_START                  1460
#define IDC_STARTCMD                    1460
#define IDC_BROWSE_BOSS                 1461
#define IDC_NOCOMPATIBILITY             1462
#define IDC_NOPOLL                      1462
#define IDC_IMPORT_DIZ                  1463
#define IDC_NOMAILERQUEUE               1463
#define IDC_NOMAIL                      1463
#define IDC_SIZE0                       1465
#define STATIC1                         1466
#define IDC_SIZE1                       1466
#define STATIC2                         1467
#define IDC_SIZE2                       1467
#define STATIC3                         1468
#define IDC_SIZE3                       1468
#define IDC_EDIT_COST                   1469
#define IDC_STATIC98                    1470
#define IDC_STATIC49                    1471
#define IDC_EDIT_WAEHRUNG               1472
#define IDC_COSTBASE                    1473
#define IDC_COMBO_DISTANCES             1474
#define IDC_BASECOSTS                   1474
#define IDC_STATIC496                   1475
#define IDC_STATIC880                   1476
#define IDC_EDIT_STARTDATE              1477
#define IDC_EDIT_ENDDATE                1478
#define IDC_STATIC573                   1479
#define IDC_CLEAR_INFO                  1480
#define IDC_SUPRESS_EMPTY               1481
#define IDC_WRITE_FILE                  1482
#define IDC_EDIT_OFFSET                 1483
#define IDC_INCOME                      1485
#define IDC_EDIT_BASEPATH               1486
#define IDC_BASEPATH                    1486
#define IDC_EDIT_FAXVIEWER              1487
#define IDC_FAXVIEWER                   1487
#define IDC_EDIT_FAXDETECTSTRING        1488
#define IDC_DONT_CONVERT                1489
#define IDC_DONT_DELETE                 1490
#define IDC_EDIT_BATCHFILE              1491
#define IDC_BROWSE_PATH                 1492
#define IDC_STATIC685                   1493
#define IDC_EDIT_FAXVIEWER_BGFAX        1493
#define IDC_FAXVIEWER_BGFAX             1493
#define IDC_STATIC687                   1494
#define ID_SORT_NAME                    1495
#define ID_SORT_COMMENT                 1496
#define ID_SORT_ADRESS                  1497
#define IDC_EDIT_MSN                    1500
#define IDC_ISDNCONECTED                1502
#define IDC_GC_1                        1503
#define IDC_MOD1IN                      1503
#define IDC_GC_2                        1504
#define IDC_MOD2IN                      1504
#define IDC_GC_3                        1505
#define IDC_ISDNIN                      1505
#define IDC_GC_4                        1506
#define IDC_MOD1OUT                     1506
#define IDC_GC_5                        1507
#define IDC_MOD2OUT                     1507
#define IDC_GC_6                        1508
#define IDC_ISDNOUT                     1508
#define IDC_MCALLS                      1509
#define IDC_MARKALLFOUND                1510
#define IDC_MCALLS2                     1510
#define IDC_MARKALLFOUNDASREAD          1511
#define IDC_SOUND_CHOICE                1512
#define IDC_TEST_SOUND                  1513
#define IDC_DD_LANGUAGE                 1514
#define IDC_EDIT_SOUND                  1515
#define IDC_CHECK_MINI                  1516
#define IDC_STATIC888                   1517
#define IDC_CHECK_ANSI                  1518
#define IDC_EDIT_STREET                 1519
#define IDC_EDIT_TOWN                   1520
#define IDC_DD_LEVEL                    1522
#define IDC_BUTTOB_FBBS                 1523
#define IDC_EDIT_PATH_FOR_FILES         1524
#define IDC_EDIT_FILESBBS               1525
#define IDC_BUTTOB_DIR                  1526
#define IDC_GLOBAL_DISABLE              1526
#define IDC_GET_PATH                    1526
#define IDC_COMBO_ADRESS                1535
#define IDC_CHECK_FALLBACK              1540
#define IDD_CFG_FONTS                   1543
#define IDC_EDIT_SPLIT_FROM             1547
#define IDC_EDIT_SPLIT_TO               1548
#define IDC_CHECK_1STMODEM              1550
#define IDC_TZ_NOT                      1550
#define IDC_CHECK_2STMODEM              1551
#define IDC_TZ_TOSS                     1551
#define IDC_TZ_DISP                     1552
#define IDC_STATIC674                   1555
#define IDC_IMPORTNOW                   1556
#define IDC_REPOST_NOW                  1556
#define IDC_DELETE_IMPORT               1557
#define IDC_DELETE_REPOST               1557
#define IDC_ASAVE                       1560
#define IDC_GEDSTYLE                    1560
#define IDC_HIDEALL                     1560
#define IDC_DOS1                        1560
#define IDC_ANSI                        1560
#define IDC_CHK_HEADER                  1560
#define IDC_MOD1SET                     1560
#define IDC_FIND                        1561
#define IDC_HIDESEL                     1561
#define IDC_DOS2                        1561
#define IDC_OEM                         1561
#define IDC_CHK_FOOTER                  1561
#define IDC_MOD2SET                     1561
#define IDC_NEW                         1562
#define IDC_DOS3                        1562
#define IDC_CHK_ORIGIN                  1562
#define IDC_OEM2                        1562
#define IDC_QUOTEA                      1563
#define IDC_DOS4                        1563
#define IDC_MACRO1                      1564
#define IDC_DOS5                        1564
#define IDC_MACRO2                      1565
#define IDC_DOS6                        1565
#define IDC_MACRO3                      1566
#define IDC_DOS7                        1566
#define IDC_MACRO4                      1567
#define IDC_DOS8                        1567
#define IDC_EXIT                        1568
#define IDC_DOS9                        1568
#define IDC_MACRO5                      1569
#define IDC_DOS0                        1569
#define IDC_QUOTE                       1570
#define IDC_WIN1                        1570
#define IDC_MSHOW                       1571
#define IDC_WIN2                        1571
#define IDC_MEVENTS                     1572
#define IDC_WIN3                        1572
#define IDC_MINFO                       1573
#define IDC_WIN4                        1573
#define IDC_MFNAME                      1574
#define IDC_WIN5                        1574
#define IDC_MCPS                        1575
#define IDC_WIN6                        1575
#define IDC_MTIME                       1576
#define IDC_WIN7                        1576
#define IDC_MTOTAL                      1577
#define IDC_WIN8                        1577
#define IDC_MTRANSF                     1578
#define IDC_WIN9                        1578
#define IDC_MSTAT                       1579
#define IDC_WIN10                       1579
#define IDC_MSESSINFO                   1580
#define IDC_DONTASAVED                  1581
#define IDC_NOT_PROC_ASAVED             1581
#define IDC_LBL_MAXUUE                  1583
#define IDC_MAXUUE                      1584
#define IDC_ALTCOLORED                  1585
#define IDC_TEARLINE                    1586
#define IDC_3                           1587
#define IDC_EDITORWIDTH                 1587
#define IDC_4                           1588
#define IDC_LBL_EDITORWIDTH             1588
#define IDC_5                           1589
#define IDC_6                           1590
#define IDC_7                           1591
#define IDC_8                           1592
#define IDC_9                           1593
#define IDC_0                           1594
#define IDC_EVENQUOTE                   1595
#define IDC_DELETE_SEENBY               1596
#define IDC_NSAVE_ORIGINAL              1597
#define IDC_LISTU                       1599
#define IDC_MAIL                        1603
#define IDC_CITY                        1604
#define IDC_MFNAME2                     1605
#define IDC_MCPS2                       1606
#define IDC_ZMODEM                      1606
#define IDC_MTIME2                      1607
#define IDC_HYDRA                       1607
#define IDC_MTOTAL2                     1608
#define IDC_PROCDELETED                 1608
#define IDC_MTRANSF2                    1609
#define IDC_ON_MARKED                   1609
#define IDC_MSTAT2                      1610
#define IDC_ON_SELECTED                 1610
#define IDC_MRESDATA                    1611
#define IDC_ON_BOTH                     1611
#define IDC_MSENDATA                    1612
#define ID_TOGGLE_USERMARK              1612
#define IDC_PROZ2                       1613
#define ID_TOGGLE_SUB_DISP              1613
#define IDC_TRANSNAME2                  1614
#define IDC_CPS2                        1615
#define ID_CTLRETURN                    1615
#define IDC_TIMEELAPSED2                1616
#define IDC_BYTESTOTAL2                 1617
#define IDC_LOCATION                    1617
#define IDC_PRENAME                     1618
#define IDC_BYTESTRANSF2                1618
#define IDC_AFTERNAME                   1619
#define IDC_PROC_HIDDEN                 1621
#define IDC_FR                          1623
#define IDC_SHOW_ATTRIBUTES             1626
#define IDC_SHOW_HIDDEN                 1627
#define IDC_SHOW_DELETED                1628
#define IDC_FILT                        1629
#define IDC_ABOUT                       1630
#define ID_AREA                         1631
#define IDC_LANGUAGE                    1633
#define IDAPPEND                        1636
#define IDC_IDLE                        1639
#define IDC_PATTERN                     1640
#define IDC_ALL                         1641
#define IDC_DIRECTION                   1642
#define IDC_MULTI                       1643
#define IDC_IGNCASE                     1645
#define IDC_USERCONV                    1646
#define IDC_UPLINK                      1648
#define IDC_COUNTER                     1656
#define IDC_ECHOTAG                     1657
#define IDC_LOGO                        1658
#define IDC_PASTESUBJ                   1660
#define IDC_ANIMAIL                     1661
#define IDC_PASTEFROM                   1661
#define IDC_ANITOSS                     1662
#define IDC_PASTETO                     1662
#define IDC_ANIPURGE                    1663
#define IDC_SUBJLIST                    1665
#define IDC_STOP1                       1667
#define IDC_STOP2                       1668
#define IDC_REPEAT_QUOTE                1670
#define IDC_SAMPLES_LIST                1671
#define IDC_LANG                        1672
#define IDC_FLIST_PATH                  1673
#define IDC_FPATH                       1674
#define IDC_EXTRACT                     1675
#define IDC_MULTISPACE                  1678
#define IDC_NDLPREFER                   1679
#define IDC_ADDMY                       1681
#define IDC_ADDHIS                      1682
#define IDC_DELMY                       1683
#define IDC_DELHIS                      1684
#define IDC_MYKLUDGE                    1685
#define IDC_HISKLUDGE                   1686
#define IDC_ORIGINFILE                  1686
#define IDC_ORIGINPATH                  1687
#define IDC_AKAROUTE                    1689
#define IDC_PATH1                       1690
#define IDC_PATH2                       1691
#define IDC_BUILTIN                     1691
#define IDC_PATH3                       1692
#define IDC_PATH4                       1693
#define IDC_SKIPFILE                    1693
#define IDC_PATH5                       1694
#define IDC_TEXTCONV                    1694
#define IDC_REMOVEFILE                  1694
#define IDC_PATH6                       1695
#define IDC_PATH7                       1696
#define IDC_RENUM                       1696
#define IDC_PATH8                       1697
#define IDC_NO_NL_REMINDER              1697
#define IDC_HIDE_CMD_WINDOW             1698
#define IDC_USEANSI                     1699
#define IDC_SCRIPTNAME                  1700
#define IDC_USEROOT                     1702
#define IDC_COND                        1705
#define IDC_TCPIP                       1706
#define IDC_LANGLIST                    1710
#define IDC_HIDE                        1712
#define IDC_CODING                      1713
#define IDC_DELETE1                     1715
#define IDC_ADD1                        1716
#define IDC_SYSNAME                     1717
#define IDC_PATH9                       1718
#define IDC_SETPAS                      1718
#define IDC_PATH10                      1719
#define IDC_BROWSER                     1720
#define IDC_PRTPROG                     1721
#define IDC_GET_FILELIST                1724
#define IDC_FOR1                        1725
#define IDC_FOR2                        1726
#define IDC_MAGIC                       1727
#define IDC_TOSSER_GRP                  1729
#define IDC_PURGER_GRP                  1730
#define IDC_MAILER_GRP                  1731
#define IDC_DELIMP                      1732
#define IDC_NOPROC_TIC                  1733
#define IDC_PNTCHECK                    1734
#define IDC_MAXCHK                      1735
#define IDC_CREATECHK                   1736
#define IDC_RECIPTTXT                   1738
#define IDC_MAXTXT                      1739
#define IDC_CREATETXT                   1740
#define IDC_MAXMAILS                    1741
#define IDC_RECIPT                      1742
#define IDC_DESCR                       1744
#define IDC_ADDDAYS                     1745
#define IDC_TEXTANSI_FONT               1748
#define IDC_SUBJLIST_FONT               1749
#define IDC_TEXTOEM_FONT                1750
#define IDC_EDITOR_FONT                 1751
#define IDC_LABELS_FONT                 1752
#define IDC_FIELDS_FONT                 1753
#define IDC_SAMPLE                      1755
#define IDC_AKAS                        1759
#define IDC_ICONS                       1760
#define IDC_SKINBR                      1761
#define IDC_SKINPATH                    1762
#define IDC_WAVEBR                      1763
#define IDC_WAVPATH                     1764
#define IDC_AVAIL                       1765
#define IDC_USED                        1766
#define IDC_NEWLINE                     1767
#define IDC_ISDNENABLE                  1768
#define IDC_USE2MODEM                   1769
#define IDC_MSN                         1770
#define IDC_RESET                       1771
#define IDC_TOPBOX                      1773
#define IDC_CUSTOM1                     1774
#define IDC_SHOWTABS                    1775
#define IDC_COLORMARK                   1776
#define IDC_BMP                         1776
#define IDC_COLOR                       1777
#define IDC_STOP                        1777
#define IDC_COLORS                      1778
#define IDC_PLAY                        1778
#define IDC_REGEXP                      1778
#define IDC_PURGEALL                    1779
#define IDC_ADDB                        1780
#define IDC_ADDU                        1781
#define IDC_DELETEB                     1782
#define IDC_DELETEU                     1783
#define IDC_CHANGEU                     1784
#define IDC_CURRENCY                    1789
#define IDC_COST                        1790
#define IDC_WORKDAYS                    1791
#define IDC_WEEKEND                     1792
#define IDC_BUTTON3                     1793
#define IDC_EVENTLOG                    1794
#define IDC_TMPL                        1795
#define IDC_ANSITEXT                    1796
#define IDC_GROUPS                      1797
#define IDC_ADDR                        1798
#define IDC_GRP                         1799
#define IDC_MINTOTRAY                   1800
#define IDC_ADDNLDATA                   1807
#define IDC_USEINIT1                    1808
#define IDC_USEINIT2                    1809
#define IDC_USEINIT3                    1810
#define IDC_USECMD1                     1811
#define IDC_USECMD2                     1812
#define IDC_USECMD3                     1813
#define IDC_CHANGE_MULTIPLE             2048
#define IDC_SETGROUP                    2048
#define ID_FILE_EXIT                    32771
#define ID_SCALE_10                     32777
#define ID_SCALE_20                     32779
#define ID_SCALE_30                     32780
#define ID_SCALE_40                     32781
#define ID_SCALE_50                     32782
#define ID_SCALE_60                     32783
#define ID_SCALE_70                     32784
#define ID_SCALE_80                     32785
#define ID_SCALE_90                     32786
#define ID_SCALE_100                    32787
#define ID_MENU_DIRECTRIES              32791
#define ID_MENU_MODEM                   32793
#define ID_MENU_PACKER                  32794
#define ID_MENU_BOSSCONFIG              32795
#define ID_MENU_NODELIST                32796
#define ID_MENU_AREAS                   32797
#define ID_CFG_SYSTEMSOUNDS             32802
#define ID_EDIT_SELECTALL               32808
#define ID_MAILCOPY                     32809
#define ID_CFG_NEWMAIL                  32810
#define ID_FILEREQUEST                  32812
#define ID_CFG_SCRIPTEDITOR             32815
#define ID_CHANGEMAIL                   32817
#define ID_CFG_DIALINGTIMEOUTS          32818
#define ID_CARBONCOPY                   32819
#define ID_ECHOLISTMANAGEMENT           32820
#define ID_AREATRAFFICINFO              32822
#define ID_CFG_OTHERCONFIGS             32826
#define ID_HELP_ABOUT                   32827
#define ID_ADDRESSINFO                  32828
#define ID_FORWARDMAIL                  32829
#define ID_SAVEMAILTOFILE               32830
#define ID_EDIT_PRINTMAIL               32831
#define ID_VIEWLOGFILES                 32832
#define ID_LOGFILE_CFG                  32833
#define ID_WINDOWSTYLE                  32836
#define ID_CFG_ADDITIONALAKAS           32837
#define ID_CFG_DISPLAYFILTER            32838
#define ID_MARKALLASREAD                32839
#define ID_ABORTSCRIPT                  32841
#define ID_NEVERPURGETHISMAIL           32842
#define ID_QUOTE_NETMAIL                32843
#define ID_RESCANMAIL                   32844
#define ID_UMLAUTCONVERT                32845
#define ID_CROSSPOST                    32846
#define ID_VIEWOUTBOUND                 32847
#define ID_CFG_TRASHCANFILTER           32849
#define ID_QUOTE                        32850
#define ID_QUOTE_A                      32851
#define ID_AUTOSAVEMAIL                 32852
#define ID_CFG_HIDESHOWICONS            32853
#define ID_STARTSCRIPT1                 32857
#define ID_STARTSCRIPT2                 32858
#define ID_STARTSCRIPT3                 32859
#define ID_STARTSCRIPT4                 32860
#define ID_FREQFROMMAIL                 32862
#define ID_MAILS_CREATENEWMAILINS       32863
#define ID_CFG_EVENTS                   32870
#define ID_MENU_MODEM2                  32872
#define ID_CFG_EDITORTYPEREPLACMENT     32873
#define ID_CFG_TEXTIMPORT               32874
#define ID_ABORTEVENT                   32875
#define ID_EXECUTEANYSCRIPT             32876
#define ID_MUL_AUTOSAVE                 32877
#define ID_MUL_DELETE                   32878
#define ID_MUL_AS_READ                  32879
#define ID_MUL_AS_PRINT                 32881
#define ID_MUL_NEVER_DELETE             32882
#define ID_PRINT_CFG                    32883
#define ID_TOGGLEROT13                  32884
#define ID_CHECKDUPES_ALL               32886
#define ID_CHECKDUPES_CURRENT           32887
#define ID_INCOMINGDEVICES              32889
#define ID_INCOMINGNUMOFRINGS           32891
#define ID_MMDISPLAYOPTIONS             32897
#define ID_MMAVAILABLEELEMENTS          32898
#define ID_CAPTURE_SENDER               32899
#define ID_CAPTURE_RECIPIENT            32900
#define ID_SUBJECT_ADJUST               32901
#define ID_REQUESTPATHS                 32902
#define ID_MAGICS                       32903
#define ID_REMOTEMONITOR                32904
#define ID_MARK_MAIL_FREEZE             32911
#define ID_CFG_TICECHOSETUP             32912
#define ID_HATCHAFILE                   32913
#define ID_BEGINMULTIUUE                32914
#define ID_ENDMULTIUUE                  32915
#define ID_UUFROMSELECTED               32916
#define ID_STARTWWWBROWSER              32918
#define ID_UNMARKALLMESSAGES            32919
#define ID_COSTCALCULATION              32923
#define ID_COSTANALYZE                  32924
#define ID_FINDORIGINAL                 32926
#define ID_INOUTCALLHISTORY             32927
#define ID_CFG_FAX                      32928
#define ID_LOCALLOGIN                   32930
#define ID_CFG_EDITORFONT               32932
#define ID_ASAVETOAREA                  32933
#define ID_POLLASYSTEM                  32934
#define ID_CFG_BBSGROUPS                32935
#define ID_CFG_BBS                      32936
#define ID_BBSUSERCONFIG                32937
#define ID_SAVEMARKEDTOAREA             32938
#define ID_BBSAREACONFIG                32939
#define IDM_ALLAREASREAD                32941
#define ID_SORT_ORDER                   32950
#define ID_SORT_RECIEVE                 32951
#define ID_SORT_CREATE                  32952
#define ID_SORT_FROM                    32953
#define ID_SORT_TO                      32954
#define ID_SORT_SUBJECT                 32955
#define ID_SORT_STATUS                  32956
#define ID_HSFLOATING                   32961
#define ID_RESET_DLGPOS                 32962
#define ID_CFG_ADRESSBOOK               32964
#define ID_MAILPRESENTAGAIN             32969
#define ID_PRESENTAGAIN                 32970
#define ID_CFG_LABELSFONT               32973
#define ID_CFG_FIELDSFONT               32974
#define ID_SWITCH_PURGER                32976
#define ID_SWITCH_MAILER                32977
#define ID_SWITCH_TOSSER                32978
#define ID_SWITCH_EXTSEARCH             32979
#define ID_SWITCH_NODELIST              32980
#define ID_SWITCH_LEFTICONS             32981
#define ID_CFG_SUBJLISTFONT             32983
#define ID_STARTSCRIPT5                 32997
#define ID_SAVESELTOFILE                32999
#define ID_FIDONET                      33001
#define ID_HELPME                       33002
#define ID_FIDOLANG                     33003
#define ID_ORDERECHOES                  33004
#define ID_STARTMAILER                  33008
#define ID_STARTTOSSER                  33009
#define ID_STARTNLCOMPILE               33010
#define ID_STARTPURGER                  33011
#define ID_HELPMAINSCREEN               33012
#define ID_SIMPLE_SEARCH                33013
#define ID_SAVE_MULTIPLE                33014
#define ID_CFG_KLUDGES                  33015
#define ID_CFG_EDITOR                   33016
#define ID_DELETE_ALL                   33017
#define ID_DICTIONARY                   33019
#define ID_INCOMING_MODEM1              33020
#define ID_INCOMING_MODEM2              33021
#define ID_DELETE_MAIL                  33022
#define ID_MAILTEXTFONT_ANSI            33023
#define ID_MAILTEXTFONT_OEM             33024
#define ID_CFG_FLOATING                 33025
#define ID_NONE                         33033
#define IDC_NEXT                        57676
#define IDC_PREV                        57677
#define IDC_FILTLIST                    57690
#define IDC_MTOT                        65527
#define IDC_BTOT                        65532
#define IDC_PTOT                        65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        568
#define _APS_NEXT_COMMAND_VALUE         33049
#define _APS_NEXT_CONTROL_VALUE         1811
#define _APS_NEXT_SYMED_VALUE           166
#endif
#endif
